/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.pascal.ide;

import org.xtext.example.pascal.ide.AbstractPascalIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PascalIdeModule extends AbstractPascalIdeModule {
}
