/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.pascal.pascal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>unsigned number</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getunsigned_number()
 * @model
 * @generated
 */
public interface unsigned_number extends any_number
{
} // unsigned_number
