/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.pascal;

import org.xtext.example.pascal.AbstractPascalRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PascalRuntimeModule extends AbstractPascalRuntimeModule {
}
