/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.pascal;

import org.xtext.example.pascal.PascalStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PascalStandaloneSetup extends PascalStandaloneSetupGenerated {
  public static void doSetup() {
    new PascalStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
