/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.pascal.pascal.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.pascal.pascal.PascalPackage;
import org.xtext.example.pascal.pascal.signed_number;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>signed number</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class signed_numberImpl extends any_numberImpl implements signed_number
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected signed_numberImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PascalPackage.Literals.SIGNED_NUMBER;
  }

} //signed_numberImpl
