/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.pascal.pascal.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.pascal.pascal.PascalPackage;
import org.xtext.example.pascal.pascal.unsigned_number;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>unsigned number</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class unsigned_numberImpl extends any_numberImpl implements unsigned_number
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected unsigned_numberImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PascalPackage.Literals.UNSIGNED_NUMBER;
  }

} //unsigned_numberImpl
