/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.pascal.ui.contentassist;

import org.xtext.example.pascal.ui.contentassist.AbstractPascalProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PascalProposalProvider extends AbstractPascalProposalProvider {
}
