/*
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.pascal


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PascalStandaloneSetup extends PascalStandaloneSetupGenerated {

	def static void doSetup() {
		new PascalStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
