/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>repetitive statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.repetitive_statement#getForStmt <em>For Stmt</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getrepetitive_statement()
 * @model
 * @generated
 */
public interface repetitive_statement extends EObject
{
  /**
   * Returns the value of the '<em><b>For Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>For Stmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>For Stmt</em>' containment reference.
   * @see #setForStmt(for_statement)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getrepetitive_statement_ForStmt()
   * @model containment="true"
   * @generated
   */
  for_statement getForStmt();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.repetitive_statement#getForStmt <em>For Stmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>For Stmt</em>' containment reference.
   * @see #getForStmt()
   * @generated
   */
  void setForStmt(for_statement value);

} // repetitive_statement
